PlantScape/PlantScape/Models/Plants.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace PlantScape.Models
{
    public class Plants
    {
        public Plants()
        {
            this.projectList = new HashSet<Projects>();
        }
        public Plants(string[] csvarray)
        {
            this.id = Convert.ToInt32(csvarray[0]);
            this.botanicalName = csvarray[1];
            this.commonName = csvarray[2];
            this.type = csvarray[3];
            this.fColorSpring = csvarray[4];
            this.fColorFall = csvarray[5];
            this.flowers = csvarray[6];
            this.leafType = csvarray[7];
            this.hardinessZone = csvarray[8];
            this.soilType = Convert.ToInt32(csvarray[9]);
            this.lightReq = csvarray[10];
            this.imageUrl = csvarray[11];
            this.projectList = new HashSet<Projects>();
            this.favoriteList = new HashSet<ApplicationUser>();
        }
        [Key]
        public int id { get; set; }
        public string botanicalName { get; set; }
        public string commonName { get; set; }
        public string type { get; set; }
        public string fColorSpring { get; set; }
        public string fColorFall { get; set; }
        public string flowers { get; set; }
        public string leafType { get; set; }
        public string hardinessZone { get; set; }
        public int soilType { get; set; }
        public string lightReq { get; set; }
        public string imageUrl { get; set; }
        public virtual ICollection<Projects> projectList { get; set; }
        public virtual ICollection<ApplicationUser> favoriteList { get; set; }
        public bool isSelected { get; set; }
        
    }
}

PlantScape/PlantScape/Controllers/PlantsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PlantScape.Models;
using System.Data.SqlClient;
using System.IO;

namespace PlantScape.Controllers
{
    public class PlantsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: PlantViewModels
        public ActionResult Index()
        {
            return View(db.Plants.ToList());
        }
        [HttpPost]
        public ActionResult Index(HttpPostedFileBase file)
        {
            var path = "";
            if (file != null && file.ContentLength > 0)
            {
                var fileName = Path.GetFileName(file.FileName);
                path = Path.Combine(Server.MapPath("~/Content/uploads"), fileName);
                file.SaveAs(path);
            }
            using (StreamReader reader = new StreamReader(path))
            {
                string line;
                while ((line = reader.ReadLine()) != null)
                {
                    string[] List = line.Split(new char[] { ',' });
                    try
                    {
                        Plants plant = new Plants();
                        plant.id = Convert.ToInt32(List[0]);
                        plant.botanicalName = List[1];
                        plant.commonName = List[2];
                        plant.type = List[3];
                        plant.fColorSpring = List[4];
                        plant.fColorFall = List[5];
                        plant.flowers = List[6];
                        plant.leafType = List[7];
                        plant.hardinessZone = List[8];
                        plant.soilType = Convert.ToInt32(List[9]);
                        plant.lightReq = List[10];
                        plant.imageUrl = List[11];
                        db.Plants.Add(plant);
                        db.SaveChanges();
                    }
                    catch
                    {
                        continue;
                    }

                }

                return RedirectToAction("Browse","Developer");
            }
        }
        // GET: PlantViewModels/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Plants plantViewModel = db.Plants.Find(id);
            if (plantViewModel == null)
            {
                return HttpNotFound();
            }
            return View(plantViewModel);
        }

        // GET: PlantViewModels/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: PlantViewModels/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,botanicalName,commonName,type,fColorSpring,fColorFall,leafType,hardinessZone,soilType,lightReq")] Plants plant)
        {
            if (ModelState.IsValid)
            {
                db.Plants.Add(plant);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(plant);
        }

        // GET: PlantViewModels/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Plants plant = db.Plants.Find(id);
            if (plant == null)
            {
                return HttpNotFound();
            }
            return View(plant);
        }

        // POST: PlantViewModels/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,botanicalName,commonName,type,fColorSpring,fColorFall,leafType,hardinessZone,soilType,lightReq")] Plants plant)
        {
            if (ModelState.IsValid)
            {
                db.Entry(plant).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(plant);
        }
         
        // GET: PlantViewModels/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Plants plant = db.Plants.Find(id);
            if (plant == null)
            {
                return HttpNotFound();
            }
            return View(plant);
        }

        // POST: PlantViewModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Plants plantViewModel = db.Plants.Find(id);
            db.Plants.Remove(plantViewModel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PlantScape/PlantScape/Views/Plants/Create.cshtml
@model PlantScape.Models.Plants
<head>
    @{
        ViewBag.Title = "Create";
        Layout = "~/Views/Shared/_Layout - Developer.cshtml";
    }
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/Fonts.css" type="text/css" rel="stylesheet" />
</head>

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.botanicalName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.botanicalName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.botanicalName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.commonName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.commonName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.commonName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.type, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fColorSpring, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fColorSpring, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fColorSpring, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fColorFall, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fColorFall, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fColorFall, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.flowers, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.flowers, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.flowers, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.leafType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.leafType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.leafType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.hardinessZone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.hardinessZone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.hardinessZone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.soilType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.soilType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.soilType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.lightReq, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.lightReq, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.lightReq, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PlantScape/PlantScape/Views/Plants/Delete.cshtml
@model PlantScape.Models.Plants

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PlantViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.botanicalName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.botanicalName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.commonName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.commonName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fColorSpring)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fColorSpring)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fColorFall)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fColorFall)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.leafType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.leafType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.hardinessZone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.hardinessZone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.soilType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.soilType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.lightReq)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.lightReq)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

PlantScape/PlantScape/Views/Plants/Details.cshtml
@model PlantScape.Models.Plants

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout - Developer.cshtml";
}

<h2>Details</h2>

<div>
    <h4>PlantViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.botanicalName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.botanicalName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.commonName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.commonName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fColorSpring)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fColorSpring)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fColorFall)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fColorFall)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.leafType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.leafType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.hardinessZone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.hardinessZone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.soilType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.soilType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.lightReq)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.lightReq)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

PlantScape/PlantScape/Views/Plants/Edit.cshtml
@model PlantScape.Models.Plants

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout - Developer.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>PlantViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.botanicalName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.botanicalName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.botanicalName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.commonName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.commonName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.commonName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.type, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fColorSpring, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fColorSpring, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fColorSpring, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fColorFall, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fColorFall, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fColorFall, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.leafType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.leafType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.leafType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.hardinessZone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.hardinessZone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.hardinessZone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.soilType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.soilType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.soilType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.lightReq, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.lightReq, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.lightReq, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PlantScape/PlantScape/Views/Plants/Index.cshtml
@model IEnumerable<PlantScape.Models.Plants>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Add a New Plant to the Database", "Create")
</p>

<p>OR</p>

@using (Html.BeginForm("Index", "Plants", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <input type="file" name="file" />
    <input type="submit" value="OK" />
}
<br />
<table class="table">
    <tr>
        <th>
           @Html.DisplayNameFor(model => model.imageUrl)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.botanicalName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.commonName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.type)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.fColorSpring)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.fColorFall)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.leafType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.flowers)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.hardinessZone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.soilType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.lightReq)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                <img src="@Html.DisplayFor(modelItem => item.imageUrl)" alt="No Image" style="width : 100%; height: 20%" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.botanicalName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.commonName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.type)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.fColorSpring)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.fColorFall)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.flowers)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.leafType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.hardinessZone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.soilType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.lightReq)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.id }) |
                @Html.ActionLink("Details", "Details", new { id = item.id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.id })
            </td>
        </tr>
    }

</table>